url: "https://gefn-rsef.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Grupo Especializado de Física Nuclear" # the name of your site, e.g. ACME Corp.
description: "Un Grupo Especializado de la Real Sociedad Española de Física"
